[functions.notify-tailors]
enabled = true
verify_jwt = false
import_map = "./functions/notify-tailors/deno.json"
entrypoint = "./functions/notify-tailors/index.ts"

[functions.create-payment-intent]
enabled = true
verify_jwt = false
entrypoint = "./functions/create-payment-intent/index.ts"

[functions.confirm-paid-order]
enabled = true
verify_jwt = false
entrypoint = "./functions/confirm-paid-order/index.ts"

[functions.stripe-webhook]
enabled = true
verify_jwt = false
entrypoint = "./functions/stripe-webhook/index.ts"

[functions.get-tailor-orders]
enabled = true
verify_jwt = false
entrypoint = "./functions/get-tailor-orders/index.ts"

[functions.update-assignment-status]
enabled = true
verify_jwt = false
entrypoint = "./functions/update-assignment-status/index.ts"
