import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:get/get.dart';
import 'package:osho/features/personalization/models/message_model.dart';
import 'package:osho/common/widgets/loaders/loader.dart';

class SupportController extends GetxController {
  static SupportController get instance => Get.find();

  final _db = FirebaseFirestore.instance;
  final _auth = FirebaseAuth.instance;

  @override
  void onInit() {
    super.onInit();
    _ensureFirebaseAuth();
  }

  Future<void> _ensureFirebaseAuth() async {
    try {
      if (_auth.currentUser == null) {
        await _auth.signInAnonymously();
      }
    } catch (e) {
      // Fail silently; support UI will show empty state if auth is unavailable.
    }
  }

  // Stream of messages for the current user
  Stream<List<MessageModel>> getMessages() {
    final userId = _auth.currentUser?.uid;
    if (userId == null) return const Stream.empty();

    return _db
        .collection('Users')
        .doc(userId)
        .collection('SupportChat')
        .orderBy('Timestamp', descending: true)
        .snapshots()
        .map((snapshot) => snapshot.docs
            .map((doc) => MessageModel.fromSnapshot(doc))
            .toList());
  }

  // Send a message
  Future<void> sendMessage(String text) async {
    try {
      final userId = _auth.currentUser?.uid;
      if (userId == null) return;

      final message = MessageModel(
        id: '', // Generated by Firestore
        senderId: userId,
        text: text,
        timestamp: DateTime.now(),
        isRead: false,
      );

      await _db
          .collection('Users')
          .doc(userId)
          .collection('SupportChat')
          .add(message.toJson());

    } catch (e) {
      OLoaders.errorSnackBar(title: 'Erreur', message: e.toString());
    }
  }
}
