// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf0Ht7Ys_pmKKaee9ipQJGDkzQmjQQAZU',
    appId: '1:639832676709:web:416a2e73945ea3b33c298c',
    messagingSenderId: '639832676709',
    projectId: 'osho-f0ba3',
    authDomain: 'osho-f0ba3.firebaseapp.com',
    storageBucket: 'osho-f0ba3.firebasestorage.app',
    measurementId: 'G-XME5GZMZ2W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZdDlSRHjZQ8HHi3e1HJl-AUqmb7_5R04',
    appId: '1:639832676709:android:64e20b5704e7f0093c298c',
    messagingSenderId: '639832676709',
    projectId: 'osho-f0ba3',
    storageBucket: 'osho-f0ba3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy77e5XD_RAaakuFwYHeec6uEqg8KR4bY',
    appId: '1:639832676709:ios:b97d5a400aaa10f53c298c',
    messagingSenderId: '639832676709',
    projectId: 'osho-f0ba3',
    storageBucket: 'osho-f0ba3.firebasestorage.app',
    androidClientId: '639832676709-gbnmn9tfv32s96qf1edslctdm22c54o6.apps.googleusercontent.com',
    iosClientId: '639832676709-psgqg446iq16vflor8kpgm49bo9nmkps.apps.googleusercontent.com',
    iosBundleId: 'com.example.osho',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAf0Ht7Ys_pmKKaee9ipQJGDkzQmjQQAZU',
    appId: '1:639832676709:web:792536a66bd2ea1b3c298c',
    messagingSenderId: '639832676709',
    projectId: 'osho-f0ba3',
    authDomain: 'osho-f0ba3.firebaseapp.com',
    storageBucket: 'osho-f0ba3.firebasestorage.app',
    measurementId: 'G-SMXVHDTNDG',
  );

}